// Auto-generated by update_bonds_v2.js
const BONDS_DB = {
  lastUpdated: 1786540303391,
  lastUpdatedDisplay: '12/8/2026, 6:41:43 pm',
  count: 2,
  bonds: [
  {
    "isin": "INE09B308044",
    "last4": "8044",
    "name": "SLICE SFB 12.00 NCD 17DE31",
    "issuer": "SLICE SMALL FINANCE BANK",
    "faceValue": 100000,
    "couponRate": 12,
    "maturityDate": "2031-12-17",
    "issueDate": "2026-03-17",
    "frequency": "Monthly",
    "rating": "BBB+",
    "bondType": "Corporate"
  },
  {
    "isin": "INE002A08286",
    "last4": "8286",
    "name": "7.18% GS 2033",
    "issuer": "GOI",
    "faceValue": 100,
    "couponRate": 7.18,
    "maturityDate": "2033-08-14",
    "issueDate": "2023-08-14",
    "frequency": "Semi-Annual",
    "rating": "SOV",
    "bondType": "G-Sec"
  }
]
};